### ISSUE TITLE
Don't show stack traces and better error messages

### ISSUE THREAD

**Issue by pglass** [pglbutt/noodles#48]
The error message situation can be much improved by:

- Adding another decorator on all the click-decorated functions that catches all `ToughNoodles` exceptions and prints the error message. 
- Also, catch `Exception` in this decorator and tell the user to report a bug.
- Requiring a message in the `ToughNoodles` constructor.
- Doing more error checking and raising more `ToughNoodles` with error messages
- Adding a debug flag of some kind to print out stack traces when we want them

**Comment by Squab** [comment]
Closing, as this all about the python version of `spag`
