### ISSUE TITLE
Panic on missing .spag directory

### ISSUE THREAD

**Issue by pglass** [pglbutt/noodles#63]
To reproduce:

    $ rm -rf .spag/
    $ spag request list
    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(2) }', ../src/libcore/result.rs:731

**Comment by Squab** [comment]
`spag history` also affected:

```
$ spag history
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:731
```

and the `spag (get|post|put|patch|delete)`'s

```
$ spag put /
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:731
```
And the subcommands for `history` and `request`
```
spag history show 0
spag request show
```

`spag env deactivate` also fails.

`spag env activate` works correctly.

```
spag env set
spag env unset
spag env show
```

All create the `.spag/environments` dir, thus creating the .spag dir.

We should probably just add a check for this in front of all commands.
